[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x2faa58"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0x2faa58"
magenta = "0xc397d8"
red = "0x8f0000"
white = "0xeaeaea"
yellow = "0xe6c547"

[colors.primary]
background = "0x000000"
foreground = "0xc9c9c9"

[colors.selection]
background = "0x404040"
text = "0xeaeaea"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
startup_mode = "Maximized"
